/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author noerommes
 */
public class FPrincipal extends javax.swing.JFrame {

    private String usuario;
    private String contraseña;
    
    
    
    public FPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        setIconImage(new ImageIcon(getClass().getResource("valencia-recuperara-escudo-1923-equipacion_58 en tamaño pequeño.jpeg.jpeg")).getImage());

    }
    
    /**
     * Hola que tal 
     * @param usuario
     * @param contraseña 
     */
    public void setDatos(String usuario, String contraseña){
        this.usuario = usuario;
        this.contraseña = contraseña;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFondo = new javax.swing.JPanel();
        tModoOscuro = new javax.swing.JToggleButton();
        eBienvenido = new javax.swing.JLabel();
        eIniciaSesion = new javax.swing.JLabel();
        eContra = new javax.swing.JLabel();
        eUsuario = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        bIniciarSesion = new javax.swing.JButton();
        tfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pFondo.setForeground(new java.awt.Color(255, 255, 255));
        pFondo.setToolTipText("");

        tModoOscuro.setFont(new java.awt.Font("LEMON MILK Light", 0, 11)); // NOI18N
        tModoOscuro.setText("MODO OSCURO");
        tModoOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tModoOscuroActionPerformed(evt);
            }
        });

        eBienvenido.setFont(new java.awt.Font("LEMON MILK", 0, 24)); // NOI18N
        eBienvenido.setText("BIENVENIDO A LA APP DEL VALENCIA C.F.");

        eIniciaSesion.setText("¡INICIA SESIÓN PARA USAR LA APP!");

        eContra.setFont(new java.awt.Font("LEMON MILK Light", 0, 24)); // NOI18N
        eContra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eContra.setText("CONTRASEÑA");
        eContra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eContra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        eUsuario.setFont(new java.awt.Font("LEMON MILK Light", 0, 24)); // NOI18N
        eUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eUsuario.setText("USUARIO");
        eUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bIniciarSesion.setBackground(new java.awt.Color(255, 153, 51));
        bIniciarSesion.setFont(new java.awt.Font("LEMON MILK", 0, 12)); // NOI18N
        bIniciarSesion.setText("INICIAR SESIÓN");
        bIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFondoLayout = new javax.swing.GroupLayout(pFondo);
        pFondo.setLayout(pFondoLayout);
        pFondoLayout.setHorizontalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(tModoOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(323, 323, 323))
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eBienvenido)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLayout.createSequentialGroup()
                        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eContra, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUser, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(tfPassword))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLayout.createSequentialGroup()
                        .addComponent(eIniciaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoLayout.createSequentialGroup()
                        .addComponent(bIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(315, 315, 315))))
        );
        pFondoLayout.setVerticalGroup(
            pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFondoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tModoOscuro)
                .addGap(32, 32, 32)
                .addComponent(eBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eIniciaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfUser)
                    .addComponent(eUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(pFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eContra, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(tfPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(bIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Configuración del objeto tModoOscuro para que cambie de color tanto el
     * fondo de la app como el texto para que sea legible con el nuevo fondo.
     *
     * @param evt
     */
    private void tModoOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tModoOscuroActionPerformed
        if (tModoOscuro.isSelected()) {

            pFondo.setBackground(Color.black);
            eBienvenido.setForeground(Color.white);
            eIniciaSesion.setForeground(Color.white);
            tModoOscuro.setText("Modo Claro");
            eUsuario.setForeground(Color.orange);
            eContra.setForeground(Color.orange);
        } else {
            pFondo.setBackground(Color.white);
            eBienvenido.setForeground(Color.black);
            eIniciaSesion.setForeground(Color.black);
            tModoOscuro.setText("Modo Oscuro");
            eUsuario.setForeground(Color.black);
            eContra.setForeground(Color.black);

        }
    }//GEN-LAST:event_tModoOscuroActionPerformed

    /**
     * Método que inicia sesión si los datos introducidos tanto en el campo usuario
     * como en el campo contraseña son válidos.
     *
     * @param evt
     */
    private void bIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarSesionActionPerformed

        if (tfUser.getText().equals(usuario)||tfPassword.getText().equals(contraseña)) {
            
            inicio sesionI= new inicio();
            sesionI.setVisible(true);
            
        }

    }//GEN-LAST:event_bIniciarSesionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();    }//GEN-LAST:event_formWindowClosing

    public void cerrar() {
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "En realidad desea realizar cerrar la aplicacion", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.NO_OPTION) {

        } else {
            System.exit(0);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIniciarSesion;
    private javax.swing.JLabel eBienvenido;
    private javax.swing.JLabel eContra;
    private javax.swing.JLabel eIniciaSesion;
    private javax.swing.JLabel eUsuario;
    private javax.swing.JPanel pFondo;
    private javax.swing.JToggleButton tModoOscuro;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables

    
}
